//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ltweb_.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class ChuyenDi
    {
        public int IdChuyenDi { get; set; }
        [DisplayName("Nơi xuất phát")]
        [Required(ErrorMessage = "Vui lòng cung cấp nơi xuất phát")]
        public string DiemXuatPhat { get; set; }
        [DisplayName("Điểm đến")]
        [Required(ErrorMessage = "Vui lòng cung cấp điểm đến")]
        public string DiemDen { get; set; }
        [DisplayName("Giá của chuyến đi")]
        [Required(ErrorMessage = "Vui lòng cung cấp giá của chuyến đi")]
        public Nullable<decimal> Gia { get; set; }
        [DisplayName("Thời gian xe đi")]
        [Required(ErrorMessage = "Vui lòng cung cấp thời gian xe đi")]
        public Nullable<System.DateTime> ThoiGianDi { get; set; }
        [DisplayName("Thời gian xe đến")]
        [Required(ErrorMessage = "Vui lòng ước lượng thời gian xe đến")]
        public Nullable<System.DateTime> ThoiGianDen { get; set; }
        [DisplayName("Chọn tài xế chính cho xe")]
        [Required(ErrorMessage = "Vui lòng chọn tài xế cho xe")]
        public Nullable<int> IdNhanVien { get; set; }
        [DisplayName("Chọn xe có biển số xe cụ thể")]
        [Required(ErrorMessage = "Vui lòng chọn biển số xe")]
        public Nullable<int> IdXeKhach { get; set; }
        public Nullable<int> IdLichTrinh { get; set; }
        [DisplayName("Địa điểm đi cụ thể")]
        [Required(ErrorMessage = "Vui lòng cung cấp nơi cụ thể")]
        public string DiemDiCuThe { get; set; }
        [DisplayName("Địa đến cụ thể")]
        [Required(ErrorMessage = "Vui lòng cung cấp nơi đến thể")]
        public string DiemDenCuThe { get; set; }
        [DisplayName("Thời gian dự kiến")]
        [Required(ErrorMessage = "Vui lòng ước lượng thời gian dự kiến")]
        public Nullable<byte> ThoiGianDuKien { get; set; }

        public virtual LichTrinh LichTrinh { get; set; }
        public virtual NhanVien NhanVien { get; set; }
        public virtual XeKhach XeKhach { get; set; }
    }
}
