//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ltweb_.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DanhSachGhe
    {
        public int IdGhe { get; set; }
        public Nullable<int> IdXeKhach { get; set; }
        public Nullable<int> SoThuTu { get; set; }
        public string TinhTrang { get; set; }
    
        public virtual XeKhach XeKhach { get; set; }
    }
}
