//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ltweb_.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DBQuanLyXeEntities : DbContext
    {
        public DBQuanLyXeEntities()
            : base("name=DBQuanLyXeEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ChuyenDi> ChuyenDi { get; set; }
        public virtual DbSet<DanhSachGhe> DanhSachGhe { get; set; }
        public virtual DbSet<HangXe> HangXe { get; set; }
        public virtual DbSet<KhachHang> KhachHang { get; set; }
        public virtual DbSet<LichTrinh> LichTrinh { get; set; }
        public virtual DbSet<NhanVien> NhanVien { get; set; }
        public virtual DbSet<ThanhToan> ThanhToan { get; set; }
        public virtual DbSet<VeXe> VeXe { get; set; }
        public virtual DbSet<XeKhach> XeKhach { get; set; }
    }
}
