//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ltweb_.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class HangXe
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HangXe()
        {
            this.NhanVien = new HashSet<NhanVien>();
            this.XeKhach = new HashSet<XeKhach>();
        }

        public int IdHangXe { get; set; }
        [DisplayName("Tên nhà xe")]
        [Required(ErrorMessage = "Vui lòng nhập tên nhà xe")]
        public string TenHangXe { get; set; }
        [DisplayName("Trụ sở chính")]
        [Required(ErrorMessage = "Vui lòng nhập địa chỉ chính của nhà xe")]
        public string DiaChiHangXe { get; set; }
        [DisplayName("Tên đăng nhập")]
        [Required(ErrorMessage = "Tên đăng nhập là bắt buộc")]
        public string TenDangNhap { get; set; }
        [DisplayName("Mật khẩu")]
        [Required(ErrorMessage = "Vui lòng nhập mật khẩu")]
        public string MatKhau { get; set; }
        [NotMapped]
        [Compare("MatKhau")]
        [DisplayName("Nhap lai mat khau")]
        public string NhapLaiMatKhau { get; set; }
        [DisplayName("Email liên hệ")]
        [Required(ErrorMessage = "Vui lòng nhập email để liên hệ")]
        public string email { get; set; }
        [DisplayName("Số điện thoại")]
        [Required(ErrorMessage = "Vui lòng nhập số điện thoại để liên hệ")]
        public Nullable<int> SoDienThoai { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NhanVien> NhanVien { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<XeKhach> XeKhach { get; set; }
    }
}

