//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ltweb_.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ThanhToan
    {
        public int IdThanhToan { get; set; }
        public Nullable<int> IdVeXe { get; set; }
        public Nullable<decimal> SoTienThanhToan { get; set; }
        public Nullable<System.DateTime> NgayThanhToan { get; set; }
        public Nullable<System.DateTime> ThoiGianThanhToan { get; set; }
    
        public virtual VeXe VeXe { get; set; }
    }
}
