//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ltweb_.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VeXe
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public VeXe()
        {
            this.LichTrinh = new HashSet<LichTrinh>();
            this.ThanhToan = new HashSet<ThanhToan>();
        }
    
        public int IdVeXe { get; set; }
        public Nullable<decimal> ThanhTien { get; set; }
        public Nullable<byte> SoLuongVe { get; set; }
        public Nullable<System.DateTime> NgayDat { get; set; }
        public string TrangThai { get; set; }
        public Nullable<int> IdLichTrinh { get; set; }
        public Nullable<int> IdKhachHang { get; set; }
        public string GhiChu { get; set; }
    
        public virtual KhachHang KhachHang { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LichTrinh> LichTrinh { get; set; }
        public virtual LichTrinh LichTrinh1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ThanhToan> ThanhToan { get; set; }
    }
}
