//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ltweb_.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Web;

    public enum LoaiXeOption
    {
        [Display(Name = "Ghế Ngồi")]
        GiuongNgoi,
        [Display(Name = "Ghế Nằm")]
        GiuongNam,
        [Display(Name = "Limousine")]
        Limousin
    }
    public static class EnumExtensions
    {
        public static string GetDisplayName(this Enum enumValue)
        {
            var fieldInfo = enumValue.GetType().GetField(enumValue.ToString());
            var descriptionAttributes = fieldInfo.GetCustomAttributes(
                typeof(DisplayAttribute), false) as DisplayAttribute[];

            if (descriptionAttributes == null || descriptionAttributes.Length == 0)
            {
                return enumValue.ToString();
            }

            return descriptionAttributes[0].Name;
        }

    }
    public partial class XeKhach
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public XeKhach()
        {
            this.ChuyenDi = new HashSet<ChuyenDi>();
            this.DanhSachGhe = new HashSet<DanhSachGhe>();
        }

        public int IdXeKhach { get; set; }
        [DisplayName("Biển số xe")]
        [Required(ErrorMessage = "Vui lòng nhập biển số xe")]
        public string BienSoXe { get; set; }
        [DisplayName("Số ghế")]
        [Required(ErrorMessage = "Vui lòng nhập số ghế cho xe")]
        public Nullable<int> SoGhe { get; set; }
        [DisplayName("Loại xe")]
        [Required(ErrorMessage = "Vui lòng chọn loại xe")]
        public string LoaiXe { get; set; }
        [DisplayName("Tên loại xe")]
        [Required(ErrorMessage = "Vui lòng nhập tên loại xe")]
        public string TenLoaiXe { get; set; }
        public Nullable<int> IdHangXe { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChuyenDi> ChuyenDi { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DanhSachGhe> DanhSachGhe { get; set; }
        public virtual HangXe HangXe { get; set; }
    }
}


